### ISSUE TITLE
Executing `mvn spring-boot: run` leads to error

### ISSUE THREAD

**Issue by johannes-kolbe** [SAP-samples/cloud-cap-samples-java#170]
Hello CAP colleagues,

we are using the `cloud-cap-samples-java` project in a test scenario to generate a Fiori elements List Report application `authors`. But currently running `mvn spring-boot:run` ends in an `BUILD SUCCESS`, but in the output an error is visible and preview is not available. 
As prerequisites the guide [Getting started](https://cap.cloud.sap/docs/java/getting-started#local) was followed:
- Platform is Mac-based, SAPMachine11/19, cds, and maven 3.8.6 installed.

Could you please advise on how to resolve this issue?

Part of Error log: 
```
ERROR 27614 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ratingCalculator' defined in file [__path__/cloud-cap-samples-java/srv/target/classes/my/bookshop/RatingCalculator.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #163 of URL [__path__/cloud-cap-samples-java/srv/target/classes/schema.sql]: CREATE TABLE my_bookshop_Books ( ID NVARCHAR(36) NOT NULL, createdAt TIMESTAMP_TEXT, createdBy NVARCHAR(255), modifiedAt TIMESTAMP_TEXT, modifiedBy NVARCHAR(255), title NVARCHAR(111), descr NVARCHAR(1111), author_ID NVARCHAR(36), genre_ID INTEGER, stock INTEGER, price DECIMAL(9, 2), currency_code NVARCHAR(3), rating DECIMAL(2, 1), isReviewable BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY(ID) ); nested exception is org.h2.jdbc.JdbcSQLNonTransientException: Unknown data type: "TIMESTAMP_TEXT"; SQL statement:
CREATE TABLE my_bookshop_Books ( ID NVARCHAR(36) NOT NULL, createdAt TIMESTAMP_TEXT, createdBy NVARCHAR(255), modifiedAt TIMESTAMP_TEXT, modifiedBy NVARCHAR(255), title NVARCHAR(111), descr NVARCHAR(1111), author_ID NVARCHAR(36), genre_ID INTEGER, stock INTEGER, price DECIMAL(9, 2), currency_code NVARCHAR(3), rating DECIMAL(2, 1), isReviewable BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY(ID) ) [50004-200]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
```

**Comment by mofterdinger** [comment]
Hi @johannes-kolbe , we fixed this issue in the main branch, please pull from main and retry.
