### ISSUE TITLE
mvn spring-boot:run fails

### ISSUE THREAD

**Issue by ullasholla** [SAP-samples/cloud-cap-samples-java#187]
Hi there,

Running `mvn spring-boot:run` at the project root fails with the exception:  `org.h2.jdbc.JdbcSQLSyntaxErrorException`.
The HEAD commit is ed14cce760be9da61192a3802d6f254778f20aa2

Excerpt from the console:
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-12-15 16:41:43.033 ERROR 57801 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ratingCalculator' defined in file [/Users/i031735/SAPDevelop/sap/cloud-cap-samples-java/srv/target/classes/my/bookshop/RatingCalculator.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #196 of URL [file:/Users/i031735/SAPDevelop/sap/cloud-cap-samples-java/srv/target/classes/schema.sql]: CREATE TABLE API_BUSINESS_PARTNER_A_SupplierCompany ( Supplier NVARCHAR(10) NOT NULL, CompanyCode NVARCHAR(4) NOT NULL, AuthorizationGroup NVARCHAR(4), CompanyCodeName NVARCHAR(25), PaymentBlockingReason NVARCHAR(1), SupplierIsBlockedForPosting BOOLEAN, AccountingClerk NVARCHAR(2), AccountingClerkFaxNumber NVARCHAR(31), AccountingClerkPhoneNumber NVARCHAR(30), SupplierClerk NVARCHAR(15), SupplierClerkURL NVARCHAR(130), PaymentMethodsList NVARCHAR(10), PaymentTerms NVARCHAR(4), ClearCustomerSupplier BOOLEAN, IsToBeLocallyProcessed BOOLEAN, ItemIsToBePaidSeparately BOOLEAN, PaymentIsToBeSentByEDI BOOLEAN, HouseBank NVARCHAR(5), CheckPaidDurationInDays DECFLOAT(3, 0), Currency NVARCHAR(5), BillOfExchLmtAmtInCoCodeCrcy DECIMAL(14, 3), SupplierClerkIDBySupplier NVARCHAR(12), ReconciliationAccount NVARCHAR(10), InterestCalculationCode NVARCHAR(2), InterestCalculationDate DATE, SupplierHeadOffice NVARCHAR(10), AlternativePayee NVARCHAR(10), LayoutSortingRule NVARCHAR(3), APARToleranceGroup NVARCHAR(4), SupplierCertificationDate DATE, SupplierAccountNote NVARCHAR(30), WithholdingTaxCountry NVARCHAR(3), DeletionIndicator BOOLEAN, CashPlanningGroup NVARCHAR(10), IsToBeCheckedForDuplicates BOOLEAN, MinorityGroup NVARCHAR(3), SupplierAccountGroup NVARCHAR(4), to_SupplierDunning_Supplier NVARCHAR(10), to_SupplierDunning_CompanyCode NVARCHAR(4), to_SupplierDunning_DunningArea NVARCHAR(2), to_SupplierWithHoldingTax_Supplier NVARCHAR(10), to_SupplierWithHoldingTax_CompanyCode NVARCHAR(4), to_SupplierWithHoldingTax_WithholdingTaxType NVARCHAR(2), PRIMARY KEY(Supplier, CompanyCode) ); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE API_BUSINESS_PARTNER_A_SupplierCompany ( Supplier NVARCHAR(10) NOT NULL, CompanyCode NVARCHAR(4) NOT NULL, AuthorizationGroup NVARCHAR(4), CompanyCodeName NVARCHAR(25), PaymentBlockingReason NVARCHAR(1), SupplierIsBlockedForPosting BOOLEAN, AccountingClerk NVARCHAR(2), AccountingClerkFaxNumber NVARCHAR(31), AccountingClerkPhoneNumber NVARCHAR(30), SupplierClerk NVARCHAR(15), SupplierClerkURL NVARCHAR(130), PaymentMethodsList NVARCHAR(10), PaymentTerms NVARCHAR(4), ClearCustomerSupplier BOOLEAN, IsToBeLocallyProcessed BOOLEAN, ItemIsToBePaidSeparately BOOLEAN, PaymentIsToBeSentByEDI BOOLEAN, HouseBank NVARCHAR(5), CheckPaidDurationInDays DECFLOAT(3[*], 0), Currency NVARCHAR(5), BillOfExchLmtAmtInCoCodeCrcy DECIMAL(14, 3), SupplierClerkIDBySupplier NVARCHAR(12), ReconciliationAccount NVARCHAR(10), InterestCalculationCode NVARCHAR(2), InterestCalculationDate DATE, SupplierHeadOffice NVARCHAR(10), AlternativePayee NVARCHAR(10), LayoutSortingRule NVARCHAR(3), APARToleranceGroup NVARCHAR(4), SupplierCertificationDate DATE, SupplierAccountNote NVARCHAR(30), WithholdingTaxCountry NVARCHAR(3), DeletionIndicator BOOLEAN, CashPlanningGroup NVARCHAR(10), IsToBeCheckedForDuplicates BOOLEAN, MinorityGroup NVARCHAR(3), SupplierAccountGroup NVARCHAR(4), to_SupplierDunning_Supplier NVARCHAR(10), to_SupplierDunning_CompanyCode NVARCHAR(4), to_SupplierDunning_DunningArea NVARCHAR(2), to_SupplierWithHoldingTax_Supplier NVARCHAR(10), to_SupplierWithHoldingTax_CompanyCode NVARCHAR(4), to_SupplierWithHoldingTax_WithholdingTaxType NVARCHAR(2), PRIMARY KEY(Supplier, CompanyCode) )"; expected ")"; SQL statement:
CREATE TABLE API_BUSINESS_PARTNER_A_SupplierCompany ( Supplier NVARCHAR(10) NOT NULL, CompanyCode NVARCHAR(4) NOT NULL, AuthorizationGroup NVARCHAR(4), CompanyCodeName NVARCHAR(25), PaymentBlockingReason NVARCHAR(1), SupplierIsBlockedForPosting BOOLEAN, AccountingClerk NVARCHAR(2), AccountingClerkFaxNumber NVARCHAR(31), AccountingClerkPhoneNumber NVARCHAR(30), SupplierClerk NVARCHAR(15), SupplierClerkURL NVARCHAR(130), PaymentMethodsList NVARCHAR(10), PaymentTerms NVARCHAR(4), ClearCustomerSupplier BOOLEAN, IsToBeLocallyProcessed BOOLEAN, ItemIsToBePaidSeparately BOOLEAN, PaymentIsToBeSentByEDI BOOLEAN, HouseBank NVARCHAR(5), CheckPaidDurationInDays DECFLOAT(3, 0), Currency NVARCHAR(5), BillOfExchLmtAmtInCoCodeCrcy DECIMAL(14, 3), SupplierClerkIDBySupplier NVARCHAR(12), ReconciliationAccount NVARCHAR(10), InterestCalculationCode NVARCHAR(2), InterestCalculationDate DATE, SupplierHeadOffice NVARCHAR(10), AlternativePayee NVARCHAR(10), LayoutSortingRule NVARCHAR(3), APARToleranceGroup NVARCHAR(4), SupplierCertificationDate DATE, SupplierAccountNote NVARCHAR(30), WithholdingTaxCountry NVARCHAR(3), DeletionIndicator BOOLEAN, CashPlanningGroup NVARCHAR(10), IsToBeCheckedForDuplicates BOOLEAN, MinorityGroup NVARCHAR(3), SupplierAccountGroup NVARCHAR(4), to_SupplierDunning_Supplier NVARCHAR(10), to_SupplierDunning_CompanyCode NVARCHAR(4), to_SupplierDunning_DunningArea NVARCHAR(2), to_SupplierWithHoldingTax_Supplier NVARCHAR(10), to_SupplierWithHoldingTax_CompanyCode NVARCHAR(4), to_SupplierWithHoldingTax_WithholdingTaxType NVARCHAR(2), PRIMARY KEY(Supplier, CompanyCode) ) [42001-214]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at my.bookshop.Application.main(Application.java:16)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

```

Full log: https://gist.github.com/ullasholla/ef6bd9fd622643058e90813b34d0bc6d

All I did was fetch the latest changes and run `mvn spring-boot:run`.

Checking out 06db082d1fdfa71921d030aea33e821f73158ec9 still works (I haven't checked the commits in between).

Am I doing anything wrong?

Cheers,
Ullas

**Comment by beckermarc** [comment]
The samples require at least `@sap/cds-dk@6.3.2`, as explained in this commit https://github.com/SAP-samples/cloud-cap-samples-java/commit/afde31b995aac4d194e807306313bcb035c8ad35.

In case you are using a globally installed @sap/cds-dk make sure to update to that version. If you are relying on a project-specific version installed to `node_modules`, please remove your `node_modules` folder to enforce an update or run the maven build with `-Dcds.install-cdsdk.force=true`, see also [Refreshing the Local cds-dk](https://cap.cloud.sap/docs/java/development/#refreshing-the-local-cds-dk)

**Comment by ullasholla** [comment]
Didn't work when I updated to `@sap/cds-dk@6.4.0`.

Forcing an update with `-Dcds.install-cdsdk.force=true` worked. Thanks
